environment: production
logging:
  level: INFO
  file: /app/logs/app.log
paths:
  data: /app/data
  outputs: /app/outputs
  logs: /app/logs
processing:
  batch_size: 1000
  max_workers: 4
api:
  host: 0.0.0.0
  port: 8000
  debug: false