name:  "era5_swe"

data_dir:  "era5_swe"

file_pattern:  "era5_swe_{year}{month}.tif"
path_template:  "E:/data/era5_swe/era5_swe_{year}{month}.tif"

data_type:  "float32"
format:  "geotiff"
variable:  "swe"

chunk_regions:  true
chunk_size:  1000

date_range:
  start:  2013-01-02
  end:  2017-12-31

fill_value:  -32768.0
valid_min:  0.0        # 有效值最小值
scale_factor:  1.0   # 单位转换系数
units:  "m"
output:
  primary_format:  "parquet"  # 输出文件格式
  always_generate_csv: true

band_per_day:  true
band_offset:  0

crs:  "EPSG:4326"
projection:  "WGS84"

debug:  true