name: CD Pipeline

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/fusing-xgb:latest .
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKER_USERNAME }}/fusing-xgb:latest

    - name: Deploy to lab workstation
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.LAB_HOST }}
        username: ${{ secrets.LAB_USERNAME }}
        key: ${{ secrets.LAB_SSH_KEY }}
        script: |
          cd /opt/fusing-xgb
          docker-compose pull
          docker-compose down
          docker-compose up -d
          docker system prune -f

    - name: Send notification
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: 🚀 Deployment completed for Fusing XGB project
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()